### ISSUE TITLE
'config.h' file not found

### ISSUE THREAD

**Issue by karthinalliyappan** [voxeet/voxeet-rn-conferencekit#2]
'config.h' file not found --> Got the error.

Environment Setup:
Xcode : 10.1
Operating system : 10.3.1
React-native : 0.57.6

Attached the screen shot for reference.
![voxeet react native issue](https://user-images.githubusercontent.com/26541759/49079324-44d20280-f266-11e8-9d9b-0a1c1b2a84b5.png)

**Comment by Comanga** [comment]
Hello, can you post on the appropriate repo please, this one is obsolete (https://github.com/voxeet/react-native-voxeet-conferencekit)?

Have you followed steps 4, 5, 6 (https://github.com/voxeet/react-native-voxeet-conferencekit#ios)?

**Comment by karthinalliyappan** [comment]
Followed the below steps:
![screen shot 2018-11-27 at 5 43 47 pm](https://user-images.githubusercontent.com/26541759/49081206-07707380-f26c-11e8-84eb-75f5a5e60225.png)

**Comment by Comanga** [comment]
Can you try cleaning your project (cmd+shift+k) and run on a real iPhone not a simulator?

**Comment by karthinalliyappan** [comment]
Run in the iPad real device got the same error.
Refer the screen shot.
![screen shot 2018 11 27 at 6 07 02 pm](https://user-images.githubusercontent.com/26541759/49082401-ad71ad00-f26f-11e8-9b55-32fbd7027df3.png)

**Comment by Comanga** [comment]
third-party is a react-native library, what happened if you generate a brand new project with: `react-native init Test` and try to building it without Voxeet?

**Comment by Comanga** [comment]
https://github.com/voxeet/react-native-voxeet-conferencekit/issues/1
